# Generated by Django 5.2.7 on 2025-10-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('option_a', models.CharField(max_length=255, verbose_name='選択肢 A')),
                ('option_b', models.CharField(max_length=255, verbose_name='選択肢 B')),
                ('option_c', models.CharField(max_length=255, verbose_name='選択肢 C')),
                ('option_d', models.CharField(max_length=255, verbose_name='選択肢 D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正解')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解説')),
                ('part', models.CharField(choices=[('PART5', 'Part 5'), ('PART7', 'Part 7')], default='PART5', max_length=5, verbose_name='パート')),
                ('difficulty_level', models.IntegerField(default=600, verbose_name='難易度レベル (目安スコア)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題一覧',
            },
        ),
    ]
